# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.8
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: kuzkingard@gmail.com
author_name: kingard
cloud_provider: netlify
preset_name: production
project_name: gora_finance-frontend

