# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: kuzkingard@gmail.com
author_name: kingard
contract_name: gora_finance
deployment_language: python
preset_name: production
project_name: gora_finance-contracts

